### PR TITLE
Add support for `aiohttp.web`

### PR DESCRIPTION
**Pull request by seandstewart**
This PR adds support for `aiohttp.web` `Response` and `Request` objects.

I made the explicit choice to require passing in the response body for validation, given it's an async operation to fetch it.

### CODE REVIEW

**Comment by seandstewart** [comment]
Hello, @p1c2u I see you are the lead maintainer for this library. Just wanted to send a ping on this PR - let me know if I've missed any steps for contributing.

**Comment by p1c2u** [comment]
Hi @seandstewart 

thank you for your contribution. It looks very good. We just need to add documentation for the integration.

**Comment by seandstewart** [comment]
> Hi @seandstewart
> 
> thank you for your contribution. It looks very good. We just need to add documentation for the integration.

Done! Also rebased off of main. There were some changes to dependencies so I had to regenerate the lockfile.

**Comment by p1c2u** [comment]
rebased to newest master

**Comment by p1c2u** [comment]
Now it's good to go. @seandstewart thank you for your work.

**Pull request merged**
